// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCO-oQ2tXXKcH75ar49TyczeVVNiHWGtr4',
    appId: '1:538523527541:android:f06f9c7e0fa94333134b3c',
    messagingSenderId: '538523527541',
    projectId: 'au-auto-5f1e1',
    databaseURL: 'https://au-auto-5f1e1-default-rtdb.firebaseio.com',
    storageBucket: 'au-auto-5f1e1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqo_qJX7GVu3GWQSPfz8wJF6xzlC0DqSs',
    appId: '1:538523527541:ios:9546d09a0e20d2f2134b3c',
    messagingSenderId: '538523527541',
    projectId: 'au-auto-5f1e1',
    databaseURL: 'https://au-auto-5f1e1-default-rtdb.firebaseio.com',
    storageBucket: 'au-auto-5f1e1.appspot.com',
    iosClientId: '538523527541-kuc8n80j04nj0p6sbpa75ae49jibkhoq.apps.googleusercontent.com',
    iosBundleId: 'com.example.auAuto',
  );
}
